pub mod a0;
pub mod a1;
pub mod a10;
pub mod a11;
pub mod a12;
pub mod a2;
pub mod a3;
pub mod a4;
pub mod a5;
pub mod a6;
pub mod a7;
pub mod a8;
pub mod a9;
pub mod sketch_utils;

pub use a0::*;
pub use a1::*;
pub use a10::*;
pub use a11::*;
pub use a12::*;
pub use a2::*;
pub use a3::*;
pub use a4::*;
pub use a5::*;
pub use a6::*;
pub use a7::*;
pub use a8::*;
pub use a9::*;

pub const A0: &str = "a0";
pub const A1: &str = "a1";
pub const A2: &str = "a2";
pub const A3: &str = "a3";
pub const A4: &str = "a4";
pub const A5: &str = "a5";
pub const A6: &str = "a6";
pub const A7: &str = "a7";
pub const A8: &str = "a8";
pub const A9: &str = "a9";
pub const A10: &str = "a10";
pub const A11: &str = "a11";
pub const A12: &str = "a12";
